### ISSUE TITLE
Gitops Setup ( Pulsar Helm )

### ISSUE THREAD

**Issue by Migorithm** [k-rustaceans/krust-web#2]

**Comment by DPS0340** [comment]
## Tasks

- [ ] git submodule 형태로 k-rustaceans Infra Repo 구성
- [ ] Pulsar Helm Chart 구성
  - [ ] AWS EBS / local-path-provisioner / ceph-block등 StorageClass 커스텀
- [ ] Argo CD App of Apps등을 활용한 Helm Chart 통합 연동

## Miscs

- Terraform 레벨의 IaC는 선택적 구현 사항
  - 구현하지 않아도 괜찮음
  - 구현한다면 EKS를 사용할 것인지, EC2 프로비저닝 + kubespray or k3sup등으로 구축할 것인지 선택
